### ISSUE TITLE
IMDb Scout

### ISSUE THREAD

**Issue by Purfview** [Aholicknight/IMDB-Scout#1]
All that stuff was fixed long time ago, maybe you didn't noticed that it continues there:

Continuation of the script is there https://greasyfork.org/en/scripts/407284-imdb-scout-mod
And there you can contribute: https://github.com/Purfview/IMDb-Scout-Mod

**Comment by Aholicknight** [comment]
@Purfview Thank you for the first issue (kinda) lol. 

I should have looked on Github for a repo or a revision of the userscript before creating this. But yes, I have fixed (most) of the problems with IMDB scout and currently works on the newer page layout for IMDB. 

Is there anything that is still broken with IMDB Scout?

**Comment by Purfview** [comment]
Something on the mobile browsers: https://github.com/Purfview/IMDb-Scout-Mod/issues/118

**Comment by Purfview** [comment]
Probably it's easy to do remote debugging, but I personally not interested much in mobile use, so I don't know when I would find time to look at it.

https://www.google.com/search?q=firefox+"remote"+"debug"+android+from+desktop

**Comment by Aholicknight** [comment]
@Purfview For mobile browsers doesn't that require root access since IMDB Scout is a userscript? I don't have an Android phone so creating a mobile port of this script would be impossible for me to do.

**Comment by Purfview** [comment]
Dunno, never tried it. I have one rooted but its screen barely works, probably would be hard to install there stuff.
There should be some emulation solutions.

**Comment by Purfview** [comment]
No need to create any "port", it works there, but some code has glitch.

**Comment by Aholicknight** [comment]
> Dunno, never tried it. I have one rooted but its screen barely works

@Purfview So this only works on rooted phones? I don't see the benefit of this userscript if it requires for the phone to be rooted in the first place + torrenting on mobile phones is slow and burns right thru data (if you were using mobile data at the time)

But for this repo, I did not add anything new _except_ fix the problems with the userscript and replace the broken torrent sites with updated URLs.

**Comment by Purfview** [comment]
I thought that you meant debugging, userscripts works normally there, rooting is not needed.

And I meant my repo, this fork is pointless as you forked an ancient 5.3.1 version, when current is 17.3.5...

**Comment by Aholicknight** [comment]
> And I meant my repo, this fork is pointless as you forked an ancient 5.3.1 version, when current is 17.3.5...

Where did you download 17.3.5 from? I downloaded the IMDB Scout script from [greasyfork](https://greasyfork.org/en/scripts/3967-imdb-scout) as that was the one I can only find.

**Comment by Purfview** [comment]
I started maintaining it from  4.12.1 version.

**Comment by Aholicknight** [comment]
@Purfview Is that available anywhere? I can only find version 5.3.1 by [kannibalox](https://greasyfork.org/en/scripts/3967-imdb-scout) and [your upload as well.](https://user-images.githubusercontent.com/7843719/190009180-42b71cac-b04a-43c2-9773-6455d92a693f.png)

**Comment by Purfview** [comment]
At kannibalox's [GitHub](https://github.com/kannibalox/IMDb-Scout), why you need it?

**Comment by Aholicknight** [comment]
> At kannibalox's [GitHub](https://github.com/kannibalox/IMDb-Scout), why you need it?

@Purfview so I can copy my fixes and use the GitHub mirror instead of the other one.
